import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from sqlalchemy import Table, Column, MetaData, Integer, String, ForeignKey, Numeric, Text, DateTime, Boolean ,create_engine
from sqlalchemy.schema import CreateTable
from sqlalchemy.dialects import postgresql, sqlite, mysql
from my_utils.validator import TableSchema, DatabaseSchema
from my_utils.llm_handler import generate_sql_func
import re

#1. The Architect (Structure)
#Design and modify your database using plain English. 
#* **Intelligent Drafting:** Generates structured JSON schemas before converting them to dialect-specific SQL via SQLAlchemy.
#* **Reflective Context:** Scans your existing database to suggest `ALTER` commands instead of creating redundant tables.
#* **Sandbox Mode:** No DB? No problem. Generate raw SQL scripts for any major dialect (Postgres, MySQL, SQLite) without a connection.

#maps sql types generated by llm  to sqlalchemy types
def map_type(type_str: str):
    type_str = type_str.lower().strip()
    
    if type_str == "int" or type_str == "integer":
        return Integer()
    elif type_str.startswith("varchar"):
        match = re.search(r'\d+', type_str)
        return String(int(match.group())) if match else String()
    elif type_str.startswith("decimal") or type_str.startswith("numeric"):
        match = re.findall(r'\d+', type_str)
        return Numeric(int(match[0]), int(match[1])) if len(match) >= 2 else Numeric()
    elif type_str == "text":
        return Text()
    elif type_str == "timestamp":
        return DateTime()
    elif type_str == "boolean":
        return Boolean()
    else:
        return String()  # fallback



def build_sql(llm_output: dict, dialect: str) -> list[str]:
    db_schema = DatabaseSchema.model_validate(llm_output)
    metadata = MetaData()
    statements = []
    for table in db_schema.tables:
        cols = []
        for col in table.columns:
            fk = ForeignKey(f"{col.foreign_key.table}.{col.foreign_key.column}") if col.foreign_key else None
            cols.append(
                Column(
                    col.name,
                    map_type(col.type),
                    fk,
                    primary_key=col.primary_key,
                    nullable=col.nullable,
                    default=col.default,
                    unique=col.unique

                )
            )
        table = Table(
            table.name,
            metadata,
            *cols
        )
        dialects = {
            "postgresql": postgresql.dialect(),
            "sqlite": sqlite.dialect(),
            "mysql": mysql.dialect()
    }

        table_statement = CreateTable(table)
        statement = str(table_statement.compile(dialect=dialects.get(dialect, postgresql.dialect())))
        statements.append(statement)
    return statements


print("genrating schema.....")
sql_query = generate_sql_func("create a database for an ecoomerce platform")
print(sql_query)
print("done")
test = build_sql(sql_query, "mysql")
print(test)